name: Node.js CI

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

env:
  BUILD_WORKER_THREADS: 4
  BUILD_SILENT: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    # strategy:
    #   matrix:
    #     node-version: [16.x, 17.x]
    steps:
    - uses: actions/checkout@v3
    # - name: Use Node.js ${{ matrix.node-version }}
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@aegenet'

    # Del old NPM
    - name: Delete old dev (belt)
      uses: aegenet/gh-delete-package-versions@v5.4.1
      with:
        package-names: 'belt,belt-crc8,belt-hide-sensitive,belt-crc32'
        package-type: 'npm'
        min-versions-to-keep: 5
        include-versions: '^999\.'
        token: ${{ secrets.DELETE_PACKAGES_TOKEN }}

    - name: Install dependencies
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: yarn run dependencies
    - name: Our dependencies
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: yarn

    - name: Clean coverages
      run: yarn run cover:clean

    - name: Lint
      run: yarn run lint

    - name: Build
      run: yarn run build

    - name: Tests
      run: yarn run test

    - name: Coverage
      run: yarn run cover

    - name: Upload coverage
      run: yarn run codecov
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Publish dev packages
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: yarn run publish

  build_pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/master'

    # strategy:
    #   matrix:
    #     node-version: [16.x, 17.x]
    steps:
    - uses: actions/checkout@v3
    # - name: Use Node.js ${{ matrix.node-version }}
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@aegenet'

    # Del old NPM
    - name: Delete old dev (belt)
      uses: aegenet/gh-delete-package-versions@v5.4.1
      with:
        package-names: 'belt,belt-crc8,belt-hide-sensitive,belt-crc32'
        package-type: 'npm'
        min-versions-to-keep: 5
        include-versions: '^999\.'
        token: ${{ secrets.DELETE_PACKAGES_TOKEN }}

    - name: Install dependencies
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: yarn run dependencies
    - name: Our dependencies
      run: yarn

    - name: Clean coverages
      run: yarn run cover:clean

    - name: Lint
      run: yarn run lint

    - name: Build
      run: yarn run build

    - name: Tests
      run: yarn run test

    - name: Coverage
      run: yarn run cover
