name: Release CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [16.x, 17.x]
    steps:
    - uses: actions/checkout@v3
    # - name: Use Node.js ${{ matrix.node-version }}
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@aegenet'

    - name: Install dependencies
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: yarn run dependencies
    - name: Our dependencies
      run: yarn

    - name: Clean coverages
      run: yarn run cover:clean

    - name: Lint
      run: yarn run lint

    - name: Build
      run: yarn run build

    - name: Tests
      run: yarn run test

    - name: Coverage
      run: yarn run cover

    - name: Publish dev packages
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: yarn run publish
