name: Release CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [16.x, 17.x]
    steps:
      - uses: actions/checkout@v4.1.7
      # - name: Use Node.js ${{ matrix.node-version }}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.x
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@aegenet'

      - name: Install dependencies
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm run dependencies
      - name: Our dependencies
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm i

      - name: Clean coverages
        run: npm run cover:clean

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test:coverage

      - name: Publish packages GitHub
        env:
          CI: true
          NPM_PUBLISH_PUBLIC: '0'
          NPM_PUSH_REGISTRY: https://npm.pkg.github.com/
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm run publish

      - name: Publish packages npm
        env:
          CI: true
          NPM_PUBLISH_PUBLIC: '1'
          NPM_PUSH_REGISTRY: https://registry.npmjs.org/
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: npm run publish
